[package]
name = "mr-kaffee-2023-22"
description = "Solution to AoC 2023/22, http://adventofcode.com/2023/day/22/"
authors = ["Peter Wieland <peter@die-wielands.net>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
