== Rust | Day 23: A Long Walk

https://rust-lang.org[Rust] solution to https://adventofcode.com/2023/day/23[AoC|2023|23].

=== Input

[source,rust,numbered]
----
include::src/lib.rs[tags=input]
----

=== Star 1

Shortest path - easy. But how do I get the longest path? Well, just try all of them...

The only interesting points in the grid are the start, the target and any coordinates, where there is actually a choice to make. So I build a grid that contains exactly those nodes with the unique distances to the neighbors as weights.

These are few enough for the problem to be solvable and to store the information which nodes have been seen in the bits of a `u64`.

The second part is the same as the first part. Just remove special treatment of slopes. This increases the number of edges in the graph and hence it runs a little longer. 

Optimizations since initial version:

- Modify graph: from the unique node from which the target is reachable, the only relevant adjacent is the target (idea from https://www.reddit.com/user/MattieShoes/[MattieShoes]): from ~330ms to ~170ms
- Prune nodes from where the target is not reachable using a graph traversal based on bit manipulations with a `u64` as 'queue' (I especially like how adjacents are filtered and 'pushed to the queue' at once using bitwise operators): from ~170ms to ~150ms
- Prune nodes from where I have been before with the same set of reachable nodes but a longer distance walked (idea from https://www.reddit.com/user/boombulerDev/[boombulerDev]): from ~150ms to ~40ms

[source,rust,numbered]
----
include::src/lib.rs[tags=solution]
----

=== Tests

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
