== Rust | Day 8: Haunted Wasteland

https://rust-lang.org[Rust] solution to https://adventofcode.com/2023/day/8[AoC|2023|8].

=== Input

The input is parsed into a tuple of a byte array representing directions and a hash map representing the map.

[source,rust,numbered]
----
include::src/lib.rs[tags=input]
----

=== Star 1

The iterator returned by `map_iter` navigates the map step by step. The solution just iterates until `ZZZ` is reached.

[source,rust,numbered]
----
include::src/lib.rs[tags=star_1]
----

=== Star 2

The solution is based on a periodicity assumption: Let `r` be the number of directions given in the puzzle input. Given any start node `A`, let `n_A` be the smallest number such that `n_A` is an integer multiple of `r` and a target node `Z` is reached after `n_A` steps. Then this situation will repeat exactly every `n_A` steps. 

In that case, the solution is the least common multiple (LCM) of all `n_A` for any possible start node `A` (for my puzzle, it turned out that any `n_A` is a prime number multiplied by `r`, so the LCM calculation could be replaced by simpler multiplications).

The periodicity assumption is essentially a guess, it cannot be derived from the puzzle description. With the feature `check-periodicity` enabled, the code will verify it (at the cost of doubling the execution time for part 2).

[source,rust,numbered]
----
include::src/lib.rs[tags=star_2]
----

=== Tests

The special "test" `test_understand` is used to get insight into to puzzle data and verify periodicity. It is supposed to run with the `--nocapture` option, because printing to `stdout` is really all it does.

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
