== Rust | Day 10: Pipe Maze

https://rust-lang.org[Rust] solution to https://adventofcode.com/2023/day/10[AoC|2023|10].

I was a little bit scared when one of the first words I read in the description was "maze"...

=== Input

I use my utility `Grid` implementation. A layer of '.' is added around the original grid to avoid special treatment of elements on the boundary.

[source,rust,numbered]
----
include::src/lib.rs[tags=input]
----

=== Star 1

Walk the loop (since we need to walk the entire loop, there is no advantage in doing a BFS), the max distance is half of the loop length (which is always even). The information which position belongs to the loop is stored in a vector of booleans.

[source,rust,numbered]
----
include::src/lib.rs[tags=star_1]
----

=== Star 2

The easy part was to figure out that a point is inside the loop if going from that point outwards, we cross the loop an odd number of times.

The tricky part was how to figure out the number of crossings. I decided to always go east. To count the number of crossings, we are only interested in the points that are contained in the pipe, and we can ignore `-` elements to which we are strictly tangent. Doing so, we just need the current and the previous element to decide whether we crossed the loop. This is the case exactly if the current element is '|' or when the previous and current element are 'L', '7' or 'F', 'J'.

My initial solution checked point by point, adding quite a bit of overhead (the solution is still available by setting feature `point-by-point`). It is a quite easy modification to count the points inside the loop line by line.

[source,rust,numbered]
----
include::src/lib.rs[tags=star_2]
----

=== Tests

I needed a few test inputs for the second part until I got all the edge cases right. The last missing step, which did actually not fail any of my tests, was to replace 'S' with the pipe type hidden below.

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
