[package]
name = "mr-kaffee-2023-25"
description = "Solution to AoC 2023/25, http://adventofcode.com/2023/day/25/"
authors = ["Peter Wieland <peter@die-wielands.net>"]
license = "MIT"
version = "0.1.1"
edition = "2021"

[dependencies]

[features]

min-cut = []
