[package]
name = "mr-kaffee-2023-00"
description = "Hello World for AoC 2023, http://adventofcode.com/2023/"
authors = ["Peter Wieland <peter@die-wielands.net>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
