[package]
name = "mr-kaffee-2023-18"
description = "Solution to AoC 2023/18, http://adventofcode.com/2023/day/18/"
authors = ["Peter Wieland <peter@die-wielands.net>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
