== Rust | Day 24: Never Tell Me The Odds

https://rust-lang.org[Rust] solution to https://adventofcode.com/2023/day/24[AoC|2023|24].

=== Input

The hail-stones are represented as an array of pairs of position and velocity. Each array element represents one dimension.

[source,rust,numbered]
----
include::src/lib.rs[tags=input]
----

=== Star 1

Part 1 is quite straight-forward. I calculate intersection points as rational numbers with numerator and denominator to avoid dealing with floating point numbers.

[source,rust,numbered]
----
include::src/lib.rs[tags=star_1]
----

=== Star 2

It took a long while until I figured that one out (and in the end, I needed a little hint from Reddit). 

I still think, there is some beauty in the locus of potential solutions in a position-velocity plane for a single dimension. For a given rock velocity, we can even use the Chinese remainder theorem to find the rock position so that there will be a collision with every hail-stone. But all this did not lead anywhere...

Yet, because it looks nice: in the picture below, 'X' marks the position (horizontal axis, left to right) and velocity (vertical axis, bottom to top) of a hail-stone and each '#' marks position and velocity of a rock that collides at some positive time.

```
#.........#..............................
..#........#.............................
....#.......#............................
......#......#...........................
..#.....#.....#..........................
#....#....#....#.........................
#...#...#...#...#........................
..#..#..#..#..#..#.......................
#.#.#.#.#.#.#.#.#.#......................
####################.....................
....................X.................... 
.....................####################
......................#.#.#.#.#.#.#.#.#.#
.......................#..#..#..#..#..#..
........................#...#...#...#...#
.........................#....#....#....#
..........................#.....#.....#..
...........................#......#......
............................#.......#....
.............................#........#..
..............................#.........#
```

The key insight was: if there is a unique solution, six equations should be enough to find it and we don't need to take care to look at integer solutions only. In theory, any hail-stone adds one unknown (the time of collision) and contributes three equations (one for every dimension), so three hail-stones should be enough to come up with the 6 equations.

Unfortunately, those equations are non-linear. But if we look at pairs of hail-stones, we can get rid of the non-linear terms. So four hail-stones or three pairs result in 6 linear equations, that I solve with Gaussian elimination. See the comments in the code for details.

[source,rust,numbered]
----
include::src/lib.rs[tags=star_2]
----

=== Geometric solution

Choose three hail-stones, say `A`, `B`, and `C`. Denote the locus of `A`, `B`, and `C` as `A(t) = xa + t dxa`, `B(t) = xb + t dxb`, and `C(t) = xc + t dxc`.

Represent those in the inertial system of `A`, i.e., `A` is placed at the origin with zero velocity. Zero velocity is important, because this results in the rock to move through the origin at some time `t_A` to collide with `A`. The locus of the hail-stones in the inertial system of `A` are `A'(t) = 0`, `B'(t) = xb' + t dxb'`, and `C'(t) = xc' + t dxc'` with vectors `xb' = xb - xa`, `dxb' = dxb - dxa`, `xc' = xc - xa`, and `dxc' = dxc - dxa`.

The locus of the rock is `R'(t) = xr' + t dxr'`. It necessarily passes through the origin for some time `t_A`. And it is supposed to intersect with the locus `B'(t)` and `C'(t)`.

The rock locus `R'(t)` contains the origin and intersects with `B'(t)` (or `C'(t)` respectively) which does contain the origin, if and only if it is contained in the plane `A-B` that is spanned by `A'` (the origin) and `B'(t)` (or `A-C` spanned by `A'` and `C'(t)` respectively). Note that the surface which contains `A'(t)` and `B'(t)` (or `C'(t)` respectively) is a plane because `A'(t)` collapses to a single point (the origin) - otherwise, we would obtain nice little https://en.wikipedia.org/wiki/Paraboloid#Hyperbolic_paraboloid[Hyperbolic paraboloids].

The rock locus `R'(t)` thus needs to be contained in the intersection of the two planes `A-B` and `A-C`. This determines the direction of the velocity vector `dxr''`, i.e., `dxr' = n dxr''` for some `n`. If we assume that the coordinates of `dxr'` are integers and if we choose `dxr''` such that the greatest common divisor of its three integer coordinates is `1`, then `n` will be an integer.

The points of collision with `B'(t)` (or `C'(t)` respectively) can be determined by calculating `t_b` and `k_b` such that `xb' + t_b dxb' = 0 + k_b dxr''` (or `t_c` and `k_c` such that `xc' + t_c dxc' = 0 + k_c dxr''`). If the problem is well posed, this yields an integer solution for `t_b` and `k_b` with `t_b > 0` (or `t_c` and `k_c` with `t_c > 0` respectively). 

The two equations `xr' + t_b dxr' = k_b dxr''` and `xr' + t_c dxr' = k_c dxr''` can be solved for `xr'` and `dxr'`: `dxr' = n dxr''` with `n = (k_c - k_b) / (t_c - t_b)` and `xr' = m dxr''` with `m = (t_c k_b - t_b k_c) / (t_c - t_b)`.


=== Tests

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
