== Rust | Day 24: Never Tell Me The Odds

https://rust-lang.org[Rust] solution to https://adventofcode.com/2023/day/24[AoC|2023|24].

=== Input

The hail-stones are represented as an array of pairs of position and velocity. Each array element represents one dimension.

[source,rust,numbered]
----
include::src/lib.rs[tags=input]
----

=== Star 1

Part 1 is quite straight-forward. I calculate intersection points as rational numbers with numerator and denominator to avoid dealing with floating point numbers.

[source,rust,numbered]
----
include::src/lib.rs[tags=star_1]
----

=== Star 2

It took a long while until I figured that one out (and in the end, I needed a little hint from Reddit). 

I still think, there is some beauty in the locus of potential solutions in a position-velocity plane for a single dimension. For a given rock velocity, we can even use the Chinese remainder theorem to find the rock position so that there will be a collision with every hail-stone. But all this did not lead anywhere...

Yet, because it looks nice: in the picture below, 'X' marks the position (horizontal axis, left to right) and velocity (vertical axis, bottom to top) of a hail-stone and each '#' marks position and velocity of a rock that collides at some positive time.

```
#.........#..............................
..#........#.............................
....#.......#............................
......#......#...........................
..#.....#.....#..........................
#....#....#....#.........................
#...#...#...#...#........................
..#..#..#..#..#..#.......................
#.#.#.#.#.#.#.#.#.#......................
####################.....................
....................X.................... 
.....................####################
......................#.#.#.#.#.#.#.#.#.#
.......................#..#..#..#..#..#..
........................#...#...#...#...#
.........................#....#....#....#
..........................#.....#.....#..
...........................#......#......
............................#.......#....
.............................#........#..
..............................#.........#
```

The key insight was: if there is a unique solution, six equations should be enough to find it and we don't need to take care to look at integer solutions only. In theory, any hail-stone adds one unknown (the time of collision) and contributes three equations (one for every dimension), so three hail-stones should be enough to come up with the 6 equations.

Unfortunately, those equations are non-linear. But if we look at pairs of hail-stones, we can get rid of the non-linear terms. So four hail-stones or three pairs result in 6 linear equations, that I solve with Gaussian elimination. See the comments in the code for details.

[source,rust,numbered]
----
include::src/lib.rs[tags=star_2]
----

=== Tests

[source,rust,numbered]
----
include::src/lib.rs[tags=tests]
----
